let datas = {
    map: [
        'wwwwwwwwwwwwwwwwwww',
        'wffffffffwffffffffw',
        'wfwwfwwwfwfwwwfwwfw',
        'wfffffffffffffffffw',
        'wfwwfwfwwwwwfwfwwfw',
        'wffffwfffwfffwffffw',
        'wwwwfwwwrwrwwwfwwww',
        'rrrwfwrrrrrrrwfwrrr',
        'wwwwfwrwwwwwrwfwwww',
        'rrrrfrrwrrrwrrfrrrr',
        'wwwwfwrwwwwwrwfwwww',
        'rrrwfwrrrrrrrwfwrrr',
        'wwwwfwrwwwwwrwfwwww',
        'wffffffffwffffffffw',
        'wfwwfwwwfwfwwwfwwfw',
        'wffwfffffffffffwffw',
        'wwfwfwfwwwwwfwfwfww',
        'wffffwfffwfffwffffw',
        'wfwwwwwwfwfwwwwwwfw',
        'wfffffffffffffffffw',
        'wwwwwwwwwwwwwwwwwww',
    ]
}